#
# Makefile for building nanosaur
#
usage:
	@echo "usage: make [download]"

0 open:
	xdg-open https://github.com/rnanosaur/nanosaur &

	#sudo bash nanosaur/nanosaur_bringup/scripts/install.sh
1 install:
	sudo apt-get install -y libffi-dev python-openssl libssl-dev
	pip install -U docker-compose

2 download:
	git clone https://github.com/rnanosaur/nanosaur.git

4 run:
	cd nanosaur; \
	docker-compose up -d

5 kill:
	cd nanosaur; \
	docker-compose down
