#
# Makefile for python sample
#
PROG=sanic

usage:
	@echo "usage: make [edit|run]"

edit e:
	vi $(PROG).py

run r:
	python3 $(PROG).py

install i:
	sudo pip3 install $(PROG)


git-update gu:
	cd ..; make gu


